apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  db_host: ZGF0YWJhc2UtMS5jOGx3ZW9naTQ0dG8udXMtZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
  db_username: Y2xvdWRfdXNlcg==
  db_password: UmF5ZWVzNzg2
